trigger: none

resources:
  pipelines:
    - pipeline: ci
      source: cmw2.ASPNETCoreEncryptedConfig-ci
      trigger:
        branches:
          include:
            - master

stages:
- stage: Deploy
  jobs:
  - deployment: Deploy_web
    displayName: 'Deploy to IIS'
    dependsOn: []
    environment:
     name: IISEncrypt
     resourceType: VirtualMachine
     tags: web
    strategy:
      rolling:
        maxParallel: 1
        deploy:
          steps:
          # - task: unzip@0
          #   inputs:
          #     pathToZipFile: '$(PIPELINE.WORKSPACE)/ci/site/WebAppThatNeedsSecrets.zip'
          #     pathToZipFolder: 'C:\inetpub\wwwroot_appsettingsencrypt'
          - task: IISWebAppDeploymentOnMachineGroup@0
            displayName: 'Deploy IIS Website'
            inputs:
              WebSiteName: 'AppSettingsEncrypt'
              Package: '$(PIPELINE.WORKSPACE)/ci/site/*.zip'
              JSONFiles: appsettings.json
              TakeAppOfflineFlag: true

