trigger: none

resources:
  pipelines:
    - pipeline: ci
      source: cmw2.ASPNETCoreEncryptedConfig-ci
      trigger:
        branches:
          include:
            - master

stages:
- stage: Deploy
  jobs:
  - deployment: Deploy
    displayName: 'Deploy to IIS'
    dependsOn: []
    environment:
     name: IISEncrypt
    strategy:
      runOnce:
        deploy:
          steps:
          - task: unzip@0
            inputs:
              pathToZipFile: '$(PIPELINE.WORKSPACE)/ci/site/WebAppThatNeedsSecrets.zip'
              pathToZipFolder: 'C:\inetpub\wwwroot_appsettingsencrypt'
          

