trigger: none

resources:
  pipelines:
    - pipeline: ci
      source: cmw2.ASPNETCoreEncryptedConfig-ci
      trigger:
        branches:
          include:
            - master

stages:
- stage: Deploy
  jobs:
  - deployment: Deploy
    displayName: 'Deploy to IIS'
    dependsOn: []
    environment:
     name: IISEncrypt
    strategy:
      runOnce:
        deploy:
          steps:
          - task: IISWebAppDeploymentOnMachineGroup@0
            displayName: 'Deploy IIS Website'
            inputs:
              WebSiteName: 'AppSettingsEncrypt'
              Package: '$(PIPELINE.WORKSPACE)/ci/site/*.zip'
              JSONFiles: appsettings.json
              TakeAppOfflineFlag: true

